### ISSUE TITLE
PL Enhancer in firefox: no menu PLE present

### ISSUE THREAD

**Issue by Owyn** [nikolay-borzov/user-scripts#64]
![image](https://user-images.githubusercontent.com/1309656/163794603-50c5e90d-00b4-4458-b8b9-b6661ae73a50.png)

**Comment by nikolay-borzov** [comment]
The menu is integrated into the site menu
![image](https://user-images.githubusercontent.com/4221449/167364318-f3e566ea-6656-4faa-b828-51ace39809e2.png)
