### ISSUE TITLE
some fix and request lazy load image support

### ISSUE THREAD

**Issue by DandyClubs** [nikolay-borzov/user-scripts#71]
some fix

id: 'imagevenue,',

const fastpic = {
id: 'fastpic',
name: 'FastPic',
linkRegExp: /fastpic\.(?:ru|org)\/view/,
imageURLRegExp: /src="(?http[^"]+)" class="image img-fluid"/,
getURL: getURLFromPage,
}

const URL_PARTS_REGEXP = /i(\d+).+\.(ru|org)\/big(\/\d+\/\d+\/).+\/([^/]+)$/
to
const URL_PARTS_REGEXP = /i(\d+).+\.(ru|org)\/big(\/\d+\/\d+\/).+\/([^\/]+)$/

ImageTwist some link include jpeg.html link extension length 4 image extension length 3
this changed xxx.jpeg to xxxjpeg

const imagetwist = {
id: 'imagetwist',
name: 'ImageTwist',
linkRegExp: /imagetwist\.com/,
viewMode: 'origin-download',

async getURL(link) {
const imageName = link.url.split('/').pop()?.replace('.html', '')
const extension = imageName?.split('.').pop() ?? ''
const imageUrl = link.thumbnailURL
.replace('/th/', '/i/')
.slice(0, -extension.length)

to

const imageName = link.split('/').pop()?.replace('.html', '')
const extension = imageName?.split('.').pop() ?? ''
const srcextension = src?.split('.').pop() ?? ''
//console.log(imageName, extension)
const imageUrl = src
.replace('/th/', '/i/')
.slice(0, -srcextension.length)

lazy load image.. src data:image.......

i check.. imagesWithLinks 

thumbnailUrl: img.src ?? img.title

get img.src  data:image....

how can change this script showInViewer to https://github.com/fengyuanchen/viewerjs

please a not only img gallery support

**Comment by nikolay-borzov** [comment]
1. I will fix issues with URL extractors
2. Could you provide mode details (examples, link HTML) regarding 

> lazy load image.. src data:image.......

3.  About

> how can change this script showInViewer to https://github.com/fengyuanchen/viewerjs

Do you miss gallery feature? If so, I'm planning to add this.
I hesitate using existing solution for viewer feature - It could have its own issues.

**Comment by DandyClubs** [comment]
i mod some code

function ImagesCollect(){
    var imagesWithLinks = [...document.querySelectorAll('a > img, a > var, a > div')]
    .map((img) => ({
        link: img.parentElement,
        thumbnailUrl: (img.src && img.src.includes('data:image') ? img.dataset.src : img.src) ?? img.title,
    }))
    .filter(({ link }) => ImagesHost.test(link.href))
    return imagesWithLinks
}

**Comment by nikolay-borzov** [comment]
What is HTML that this code handles?

**Comment by DandyClubs** [comment]
from this code 

  const imagesWithLinks = $$('a > img, a > var', container)
    .map((img) => ({
      link: img.parentElement,
      thumbnailUrl: img.src ?? img.title,
    }))
    .filter(({ link }) => link.href)


some site lazy load image src is data:image........ or 1x1 transparent image
